title: Wonchan Choi
description: Dr. Choi's Website
theme: just-the-docs

#url: https://just-the-docs.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: foo

footer_content: "Copyright &copy; 2024 Wonchan Choi 
Last Update: 2024-01-04"

footer_content: "Last update: January 4, 2024"

last_edit_timestamp: true

last_edit_time_format: "%b %e %Y at %I:%M %p" 

# uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
